source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'pg'
gem 'mongrel'
gem 'devise'
gem 'simple_form'
gem 'paper_trail'
gem 'roo'
gem 'zip'
gem 'spreadsheet'
gem 'google-spreadsheet-ruby'
gem 'chronic'