source 'http://rubygems.org'

gem 'rails'
gem 'devise'
gem 'simple_form'
gem 'paper_trail'
gem 'roo'
gem 'zip'
gem 'spreadsheet'
gem 'google-spreadsheet-ruby'
gem 'chronic'
gem 'paperclip-cloudfiles'
gem 'cloudfiles'
gem 'inploy'
gem 'shadow_puppet'
gem "mongrel"
gem 'pg'
