development:
  adapter: postgresql
  encoding: unicode
  database: qualidade_development
  pool: 5
  username: sanderson
  password: 072029

test:
  adapter: postgresql
  encoding: unicode
  database: qualidade_test
  pool: 5
  username: sanderson
  password: 072029

production:
  adapter: postgresql
  encoding: unicode
  database: qualidade_production
  pool: 5
  username: sanderson
  password: 072029
  host: localhost
  port: 5432
