development:
  container: qualidade_desenvolvimento
  username: gilsantana
  api_key: bd4bd8210bb0a00afe880a5cb1bfb670

test:
  container: pcdemo_test
  username: 
  api_key: 

production:
    container: qualidade_producao
    username: gilsantana
    api_key: bd4bd8210bb0a00afe880a5cb1bfb670
